# Configare the automatic respawn by set_time command (in minits)
# Possible colors https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
## Percentages are calculated between 0.0(0%) and 1.0(100%)
## You can add unlimited rewards
# To create more custom ArmorStand o modify this one, use https://haselkern.com/Minecraft-ArmorStand/
# Abilites: When you attack the dragon, a random skill will be used, configute it individually

options:
  automatic_respawn: true
  bossbar_color: PURPLE
  name_visible: false
  dragon_damage_enderman: false
  enderman_target_dragon: false
  disable_endcrystal_onbedrock:
    worlds:
    - world_the_end

abilities:
  counter_attacks:
    lightning:
      chance: 0.3
      msg_to_player: "&5Dragon: &7You cant against my power"
    dodge:
      chance: 1.0
      msg_to_player: "&5Dragon: &7You failed, you are worth nothing"
    impulse:
      chance: 0.3
      msg_to_player: "&5Dragon: &7Agggggrhh"
    explosion:
      chance: 0.3
      msg_to_player: "&5Dragon: &7Dieeeeee!!"  
    ender_attack:
      chance: 0.15
      msg_to_player: "&5Dragon: &7Attack endermans!!"  
      radius: 20

drops:
  egg: 0.15
  head: 0.15

rewards:
  1:
    chance: 1.0
    broadcast_text: ""
    drops: 
    - ENDER_EYE
    - BONE
    commands: 
    - eco give %player% 100
    - give %player% diamond 4
  2:
    chance: 0.50
    broadcast_text: ""
    drops: 
    - BONE
    commands: 
    - eco give %player% 100
    - give %player% emerald 4
  3:
    chance: 0.0
    broadcast_text: "Example: 0%"
    drops: 
    - DIAMOND 

messages:
  respawn: "&7The &5Ender Dragon &7has respawned."
  onkill: "&7The player &c%player% &7has kill the &5Ender Dragon."
  dropegg: "&7You have killed the dragon and its egg has fallen in the place of his death."
  drophead: "&7You have killed the dragon and its head has been dropped."
  endcrystal: "&cYou cant use ender crystal on bedrock."
  next_dragon: "&7%hours% hours and %min% minutes"

leaderboard:
  prefix: "&c"
  separator: " &7> &e"
  suffix: " &7kills"

statue:
  baseplate: false
  gravity: false
  small: false
  name_visible: true
  name: "DragonKiller %player%" 
  chestplate: DIAMOND_CHESTPLATE
  boots: DIAMOND_BOOTS
  leggings: DIAMOND_LEGGINGS
  mainhand: DIAMOND_SWORD
  offhand: DRAGON_HEAD
  leftarm:
    x: 278
    y: 338
    z: 0
  rightarm:
    x: 290
    y: 338
    z: 100
  rightleg:
    x: 10
    y: 0
    z: 10
  leftleg:
    x: 338
    y: 0 
    z: 345
  head:
    x: 10
    y: 350
    z: 0